site_name: weka-virtualenv
theme: readthedocs
repo_url: https://github.com/fracpete/weka-virtualenv
site_description: weka-virtualenv Documentation
pages:
    - Home: index.md
    - Commands: commands.md
    - Examples: examples.md
    - Maven: maven.md
    - Releases: releases.md

